### PR TITLE
Support subdatasets

### LINKED ISSUE #18: Support subdatasets
Only installed ones - no need to install. But I guess we need to (re) introduce ability to deduce dataset for unseen yet paths (ie cache association between directories and datasets they belong to)

### PR DESCRIPTION
**Pull request by jwodder**
Closes #18.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Great, thank you!  Could you please try it on dandisets superdataset and some (i.e. do not install full hierarchy but e.g. some from within `/labs` and `/openneuro` ) from  http://datasets.datalad.org/?

**Comment by jwodder** [comment]
@yarikoptic I'm not clear on exactly what sort of setup you're asking me to test.

**Comment by yarikoptic** [comment]
smth like `datalad install ///dandi/dandisets; cd dandisets; datalad install 00000*; fuse mount $PWD to new location and cd there; dandi ls 00000*/*/*nwb` and similarly for `datalad install ///; cd datasets.datalad.org; datalad install -r labs/haxby ; fuse mount $PWD to some location; pip install nibabel; find labs -iname *nii.gz | xargs -n 10 nib-ls `

**Comment by jwodder** [comment]
@yarikoptic Observations so far (will be updated as more processes finish):

* Mounting works fine, but traversing the mount is slow.
* Running just `ls 00000*/*/*nwb` (no `dandi`) or `find . -name '*.nwb'` on the Dandisets dataset takes 26 minutes.  For most of that time, the two processes were running in parallel without any apparent problems.

**Comment by yarikoptic** [comment]
hm. do you see some obvious reason for slowness in the code? (how many files was it?) may be something to address?

still curious how "efficient" (in storage/time) `dandi ls` on a sample subdataset without too many nwb files would be.

**Comment by jwodder** [comment]
@yarikoptic There are 1944 NWB files in the installed subdatasets, so about 0.8 seconds per file.  I believe the slowness is due to the massive number of git-annex calls and HTTP requests.

**Comment by yarikoptic** [comment]
re annex calls -- lets switch to use `--batch` mode for as many or at least the bottleneck invocations. e.g. there is a `batch` option for `annex.whereis`, so that one is easy.  For `examinekey` -- just do smth like

```python
            bcmd = self._batched.get('examinekey', annex_options=....whateverneeded...,
                                     json=True, path=self.path)
            json_objects = bcmd(key)
```
or alike (just copied/mutated from `whereis` code in datalad.support.annexrepo).  batched calls should be much faster since would reuse existing process from previous call.

With big hierarchies we might breed too many of such batched processes lingering around, but we can work out some GC (at datalad package level) as need arises.

**Comment by jwodder** [comment]
@yarikoptic A problem I encountered: Running `dandi ls` caused fsspec to download the NWB files and keep them in the dataset's cache, leading to the 20GB disk on my Vagrant box eventually reaching 100%.  I suspect this may have been the cause of the bus error/segfault I mentioned in my "Observations" comment above.

**Comment by jwodder** [comment]
@yarikoptic Batching `whereis` and `examinekey` brought the runtime of `find . -name '*.nwb'` down to just under 22 minutes.  Barely an improvement.

**Comment by yarikoptic** [comment]
Timing: indeed. Need to profile I guess on what takes time, especially on subsequent call on the same mount - it shouldn't need to access git annex or web I think

**Comment by yarikoptic** [comment]
BTW, can a fuse mount async somehow? Ie if multiple processes access different files in parallel - does fuse allow for that or they would be serialized?

**Comment by jwodder** [comment]
@yarikoptic I ran `hexdump` on two different files in two different windows, and the processes ran in parallel without any apparent issues.

**Comment by yarikoptic** [comment]
> @yarikoptic I ran `hexdump` on two different FUSEd files in two different windows, and the processes ran in parallel without any apparent issues.

that is oddly cool ;)

**Comment by yarikoptic** [comment]
Well, if we stop caring for unlocked files, and we already stopped carrying about non POSIX filesystems - instead of them can just rely on symlink analysis, which should be fast! Adding lru cache on top (under read only/ immutability assumption) should get subsequent calls instantaneous

**Comment by yarikoptic** [comment]
to get any reasonable performance I think we should indeed forget about "proper" annex interfaces for symlinks which have `.git/annex/objects` in them -- those would point to the top location of the dataset to use, and guarantee that the file is under annex.
For files which are not symlinks:  if larger than 1kB -- consider it to be a "real file", already present.  if smallish - might be unlocked file under annex and contain a link inside. that might be the only case where to ask annex "properly" to discover for sure.

**Comment by jwodder** [comment]
@yarikoptic FYI, running the tests on commits dcfa8ba and ffba02b fails on my machine, both inside & outside the Vagrant box.  Inside the box, the tests are suddenly killed, while outside I get a "Too many open files" error.  I suspect this may be due to some bug in datalad.  (Not sure why the tests pass on GitHub Actions, though.)

**Comment by yarikoptic** [comment]
for heavy hierarchies, as I have [mentioned above](https://github.com/datalad/datalad-fuse/pull/19#issuecomment-964408821) we might better establish automagic "cleanup" of batched processes and better be done at datalad level IMHO.  Filed a dedicated issue for that https://github.com/datalad/datalad/issues/6197 .

**Comment by jwodder** [comment]
@yarikoptic Even after removing several `git-annex` calls in favor of symlink analysis, the runtime of `find . -name '*.nwb'` is still only at 18 and a half minutes.

**Comment by yarikoptic** [comment]
and what does it spend time on?  may be you could see quickly with https://github.com/benfred/py-spy on that process?

**Comment by jwodder** [comment]
@yarikoptic As far as I can tell from py-spy's flame graph, runtime seems to be almost evenly split between stuff in `fsspec/implementations/cached.py` and `open()` in `fsspec/spec.py`.

**Comment by jwodder** [comment]
@yarikoptic Running the tests with the current master branch of datalad succeeds without having too many git-annex processes open at once, though note that I already addressed this problem with commit 2286688.

**Comment by yarikoptic** [comment]
if I get right with that commit we would start a new batched process per each file -- that kinda ruins the entire point of having those batched processes since we do want to reuse them across files, so may be it should be reverted (or have I missed that point of that commit?)

**Comment by jwodder** [comment]
@yarikoptic Even without that commit, we're using a new batched process for each file, as each call to `fsspec-head` creates a new `FsspecAdapter`.

**Comment by yarikoptic** [comment]
> @yarikoptic Even without that commit, we're using a new batched process for each file, as each call to `fsspec-head` creates a new `FsspecAdapter`.

hm, we should avoid that. That is probably what contributes to the overall slowness.  But I think we should just proceed with this PR merged and I will file a dedicated issue on needed RFing to have the "fuse" component not create new FsspecAdapter's/batched proceeses per each file. (I will merge but feel welcome to follow up to cleanup my misunderstanding of the situation if I am wrong)

**Comment by jwodder** [comment]
@yarikoptic The slowness is unrelated, as `fusefs` doesn't use `fsspec-head`.  The `fusefs` process maintains a single `FsspecAdapater` over its run, with one `AnnexRepo` instance per (sub)dataset.

**Pull request merged**
