### PR TITLE
RF invocation of codecov following datalad setup

### LINKED ISSUE #12: Update Appveyor config to use new codecov uploader
On June 9, codecov released a new version of their coverage uploader program to replace the old bash uploader, which will stop working on February 1 and is currently experiencing scheduled brownouts; see [this blog post](https://about.codecov.io/blog/introducing-codecovs-new-uploader/) for more information.  The Appveyor config must be updated to install the new codecov uploader; see the linked blog post for instructions.

### PR DESCRIPTION
**Pull request by yarikoptic**
Closes #12

### CODE REVIEW

**Comment by jwodder** [comment]
@yarikoptic Does this repository even use Appveyor?  There are no Appveyor checks listed for this PR, for one.

**Comment by yarikoptic** [comment]
buga ga, indeed!  and the whole `fuse` layer is anyways linux specific.  Let me just remove this file and still close that issue with this PR.  We might get back to appveyor (but later).

**Comment by jwodder** [comment]
@yarikoptic The Appveyor badge should also be removed from the README.

**Comment by yarikoptic** [comment]
indeed, thanks, done!

**Pull request merged**
