### PR TITLE
Don't pretend non-objects/ entries in .git/annex exist

### LINKED ISSUE #49: restrict "fake .git/annex/objects" directory more
we got pybids failing because we pretend for this file/directory to exist 

```
$> ls -l .git/annex/layout_config.json
total 0
```
and we should only pretend for `.git/annex/objects` and its subdirectories to keys

### PR DESCRIPTION
**Pull request by jwodder**
Closes #49.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Thank you @jwodder -- this fixes what was reported. But the target use case is a bit more obnoxious: pybids tries to access now that file deeper under `objects/`: `/tmp/mnt/openneuro/ds000001/.git/annex/objects/layout_config.json` .  While at it, please adjust PR to match objects key hash directories there only, such as

```shell
$> ls -l .git/annex/objects 
total 0
drwx--S--- 1 yoh yoh 4 Feb  1 09:38 Kv/
drwx--S--- 1 yoh yoh 4 Feb  1 09:37 Mv/
drwx--S--- 1 yoh yoh 4 Feb  1 09:40 g6/
``` 
which I guess are the two alphanumerics.  For the rest should be `None`.

**Comment by jwodder** [comment]
@yarikoptic Should only directories immediately under `.git/annex/objects` be required to be two alphanumeric characters, or also the directories immediately underneath them?  (Note that directories at the third level do not match this pattern.)

**Comment by yarikoptic** [comment]
> @yarikoptic Should only directories immediately under `.git/annex/objects` be required to be two alphanumeric characters, or also the directories immediately underneath them? (Note that directories at the third level do not match this pattern.)

I think checking only immediately under would be sufficient, but it would not hurt to test one level more. Indeed next level then corresponds to key directories of different pattern, let's ignore those for now.  An idea for more "specific" matching filed as https://github.com/datalad/datalad-fuse/issues/53  but I do not think we would need to pursue it (unless some obnoxious software would start looking for some conflicting with git-annex cache directories name)

**Comment by jwodder** [comment]
@yarikoptic Done: 46bc151

**Comment by yarikoptic** [comment]
Thank you!  Unfortunately pybids case is still giving me troubles.  I have pushed 1a5b6eb5e2cf365724647d233f958cc9de6cbfe1 which I thought would address its peeking under key directories we actually might have (some keys were retrieved in that git-annex repo) but it seems still insufficient and errors are confusing to me.  Citing from that commit message - may be you have some ideas on what else could be going on?

<details>
<summary>In the use case of bids metadata extractor seems still insufficient
</summary> 

- in datalad metadata extractor window we get logged

      File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/lib/python3.9/site-packages/bids/layout/index.py", line 193, in _index_dir
        self._index_dir(d, list(config), default_action=default)
      File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/lib/python3.9/site-packages/bids/layout/index.py", line 193, in _index_dir
        self._index_dir(d, list(config), default_action=default)
      [Previous line repeated 3 more times]
      File "/home/yoh/proj/datalad/datalad-metalad/venvs/dev3/lib/python3.9/site-packages/bids/layout/index.py", line 163, in _index_dir
        if config_file.exists():
      File "/usr/lib/python3.9/pathlib.py", line 1424, in exists
        self.stat()
      File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
        return self._accessor.stat(self)
    OSError: [Errno 34] Numerical result out of range: '/tmp/mnt/openneuro/ds000001/.git/annex/objects/Mv/8q/MD5E-s669578--0017a7174b9fdebeb1e57f36027bfb96.nii.gz/layout_config.json'

    > /usr/lib/python3.9/pathlib.py(1232)stat()
    -> return self._accessor.stat(self)

- in datalad fusefs  process we get logged

    [DEBUG  ] /home/yoh/datalad/openneuro/ds000001/.git/annex/objects/Mv/8q/MD5E-s669578--0017a7174b9fdebeb1e57f36027bfb96.nii.gz/layout_config.json: path resolved to .git/annex/objects/Mv/8q/MD5E-s669578--0017a7174b9fdebeb1e57f36027bfb96.nii.gz/layout_config.json in dataset at /home/yoh/datalad/openneuro/ds000001
    [DEBUG  ] .git/annex/objects/Mv/8q/MD5E-s669578--0017a7174b9fdebeb1e57f36027bfb96.nii.gz/layout_config.json: under annex, does not have content
    [DEBUG  ] .git/annex/objects/Mv/8q/MD5E-s669578--0017a7174b9fdebeb1e57f36027bfb96.nii.gz/layout_config.json: opening via fsspec
    [DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'whereis', '--key', 'layout_config.json', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true'] (cwd=/home/yoh/datalad/openneuro/ds000001)
    [DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'whereis', '--key', 'layout_config.json', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true'] with status 1
    [WARNING] Process <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...> was terminated with returncode 1
    [DEBUG  ] Closing stderr of <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...>
    [DEBUG  ] Closing stdin of <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...> and waiting process to finish
    [DEBUG  ] Process <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...> has finished
    [WARNING] Restarting the process due to previous failure
    [DEBUG  ] Initiating a new process for BatchedAnnex(cmd=<<['git', '-c', ++117 chars++ch']>>, output_proc=<function>, path=<<'/home/yoh/dat++20 chars++001'>>)
    [WARNING] Process <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...> was terminated with returncode 1
    [DEBUG  ] Closing stderr of <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...>
    [DEBUG  ] Closing stdin of <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...> and waiting process to finish
    [DEBUG  ] Process <Popen: returncode: 1 args: ['git', '-c', 'diff.ignoreSubmodules=none', 'ann...> has finished
    [WARNING] Restarting the process due to previous failure
    [DEBUG  ] Initiating a new process for BatchedAnnex(cmd=<<['git', '-c', ++117 chars++ch']>>, output_proc=<function>, path=<<'/home/yoh/dat++20 chars++001'>>)
    Exception ignored on calling ctypes callback function: functools.partial(<function FUSE._wrapper at 0x7fab1156c280>, <bound method FUSE.getattr of <fuse.FUSE object at 0x7fab10840cd0>>)
    Traceback (most recent call last):
      File "/home/yoh/proj/datalad/datalad-fuse/venvs/dev3/lib/python3.9/site-packages/fuse.py", line 756, in _wrapper
        self.__critical_exception = e
    NameError: name 'self' is not defined
    fuse: bad error value: 317901728

</details>

**Comment by jwodder** [comment]
@yarikoptic The second problem is [a fusepy bug in error handling](https://github.com/fusepy/fusepy/pull/142).

As for the first problem, do you know exactly what the metalad extractor is doing?  It looks to me like it's traversing every directory in the given hierarchy looking for a `layout_config.json` file.  At the very least, it should exclude `.git/` directories from this search.

**Comment by yarikoptic** [comment]
> @yarikoptic The second problem is [a fusepy bug in error handling](https://github.com/fusepy/fusepy/pull/142).

THANK YOU! and damn -- I either forgot or did not know that fusepy is not actively maintained!  That sucks... yet to decide what we should do in the long run. Re this specific error  - I guess it is due to underlying problem in our code one way or another, and just reporting is off since even if I just `ls` that path, I get similar ugly "Numerical result out of range". Found others experiencing similar issue, e.g. [this issue](https://github.com/mar-file-system/marfs/issues/152) with [this fix](https://github.com/mar-file-system/marfs/commit/937ea21a5a6a9c6800b283d03a0dfda838a4d66b) . May be you have a clue where our code could lead to some errorring out?

> As for the first problem, do you know exactly what the metalad extractor is doing? It looks to me like it's traversing every directory in the given hierarchy looking for a `layout_config.json` file. At the very least, it should exclude `.git/` directories from this search.

did not look in the code but your guess aligns with mine.  yes, we can/should make it exclude `.git/` but I am taking these failures as a good smoke/use testing to ensure that nothing else would cause us trouble as well ;-)

**Comment by yarikoptic** [comment]
well, `test_fuse_subdataset` for `transparent`  mode fails now, so I guess my fix broke something.

**Comment by jwodder** [comment]
@yarikoptic You got the key regex wrong, so the `URL--http&c%%127.0.0.1&c55485%binary.png` keys used in the tests weren't being recognized.  I've corrected the regex following https://git-annex.branchable.com/internals/key_format/.

**Comment by yarikoptic** [comment]
> @yarikoptic You got the key regex wrong, so the `URL--http&c%%127.0.0.1&c55485%binary.png` keys used in the tests weren't being recognized. I've corrected the regex following https://git-annex.branchable.com/internals/key_format/.

oh, thank you!  I dug deeper, might send as a separate PR -- thinking to reuse logic of the `is_annex_dir_or_key`...

**Comment by yarikoptic** [comment]
Thank you @jwodder! Let's proceed.  Will send follow up PR separately (this alone is not sufficient to please pybids)

**Pull request merged**
